### ISSUE TITLE
Some repositories missing from results

### ISSUE THREAD

**Issue by graham73may** [phillipj/gitlab-search#14]
Hi,

**Description of problem**
I'm scanning my repos for part of a htaccess rule using:
`gitlab-search "download.php?file" -f ".htaccess"`

**Expected result**
I expected to get about 5 different results but only got 3. 

I manually verified the missing repos did have the string in a htaccess file. 

**Notes**
All of the repos are owned by the group the dev team are a part of (no personal repos). 

Comparing a repo that is found vs one that isn't I can't see any standout differences in the settings. 

Thanks for the great little tool by the way! 
( *grumbles about how Gitlab needs global search* )

**Comment by phillipj** [comment]
Hi there @graham73may!

Thanks for the detailed report.

I don't have an immediate suspect I'm afraid. Having the ability to enable debug logs have bugged me for a while, and your example serves as a good example why that would have been extremely valuable.

Before any logs can be enabled tho, the only thing I can think of that _might_ give us some clues would be to manually perform some of the HTTPS requests that `gitlab-search` does for us under the hood.

Would you be comfortable with trying a few requests like that if I provided some `curl` commands for you to execute?

**Comment by graham73may** [comment]
Hi @phillipj! 

Of course, anything I can do to help 🙂.

(Not currently at a computer so can't help right this second but can report back ASAP).

**Comment by phillipj** [comment]
Cool, thx! No worries, I certainly don't expect immediate response, so take your time 😄

I'll do my best to get some examples requests up within the upcoming week.

**Comment by phillipj** [comment]
Got a bit delayed on these `curl` commands, sorry.

Here's the requests the `gitlab-search` tool does programatically behind the scenes:

```
# 1. Get all groups
$ curl -H 'Private-Token:YOUR_PRIVATE_API_TOKEN' https://gitlab.com/api/v4/groups?per_page=1000

# 2. Get all projects per group
$ curl -H 'Private-Token:YOUR_PRIVATE_API_TOKEN' https://gitlab.com/api/v4/groups/GROUP_ID/projects?per_page=1000

# 3. Search for contents per project
$ curl -H 'Private-Token:YOUR_PRIVATE_API_TOKEN' https://gitlab.com/api/v4/projects/PROJECT_ID/search?scope=blobs&search=download.php%3Ffile filename:.htaccess
```

Where you have got to replace `YOUR_PRIVATE_API_TOKEN | GROUP_ID | PROJECT_ID` where those are present. Don't hesitate to shout if anything is unclear!

Sooo the big question is ofcourse; do you see those projects you're missing? If so, are there any search results when doing step 3?

**Comment by graham73may** [comment]
Hi @phillipj 

Thanks for following up!

Step 1: Works fine
Step 2: Works... but the missing project is still **not** there!
Step 3: Works for projects it did find in step 2. 

I found the project_id the long way in Gitlab's UI and ran this command, which **did** correctly return the project info.

```
# Get a Project
$ curl -H 'Private-Token:YOUR_PRIVATE_API_TOKEN' https://gitlab.com/api/v4/projects/PROJECT_ID
```

Then I tried your step 3 command putting the project ID in and it **did** find the correct results
```
# 3. Search for contents per project
$ curl -H 'Private-Token:YOUR_PRIVATE_API_TOKEN' https://gitlab.com/api/v4/projects/PROJECT_ID/search?scope=blobs&search=download.php%3Ffile filename:.htaccess
```

**Comment by graham73may** [comment]
I've been working a lot in Powershell lately, some PS commands if that's useful for anyone reading this: 

```
# 1. Get all groups
$ curl -H 'Private-Token:YOUR_PRIVATE_API_TOKEN' https://gitlab.com/api/v4/groups?per_page=1000

> Invoke-RestMethod -Headers @{"Private-Token" = "YOUR_PRIVATE_API_TOKEN"} -Uri https://gitlab.com/api/v4/groups?per_page=1000


# 2. Get all projects per group
$ curl -H 'Private-Token:YOUR_PRIVATE_API_TOKEN' https://gitlab.com/api/v4/groups/GROUP_ID/projects?per_page=1000

> Invoke-RestMethod -Headers @{"Private-Token" = "YOUR_PRIVATE_API_TOKEN"} -Uri https://gitlab.com/api/v4/groups/GROUP_ID/projects?per_page=1000


# 3. Search for contents per project
$ curl -H 'Private-Token:YOUR_PRIVATE_API_TOKEN' https://gitlab.com/api/v4/projects/PROJECT_ID/search?scope=blobs&search=download.php%3Ffile filename:.htaccess

> Invoke-RestMethod -Headers @{"Private-Token" = "YOUR_PRIVATE_API_TOKEN"} -Uri "https://gitlab.com/api/v4/projects/PROJECT_ID/search?scope=blobs&search=download.php%3Ffile filename:.htaccess"


# Get a Project
$ curl -H 'Private-Token:YOUR_PRIVATE_API_TOKEN' https://gitlab.com/api/v4/projects/PROJECT_ID

> Invoke-RestMethod -Headers @{"Private-Token" = "YOUR_PRIVATE_API_TOKEN"} -Uri "https://gitlab.com/api/v4/projects/PROJECT_ID"
```

**Comment by graham73may** [comment]
I've found that step 2 is giving me 100 results for the "Projects by Group" API call.... which is a suspiciously round number. 

Just found this in the API Docs: 
> **Disabling the results limit**
> The 100 results limit can be disabled if it breaks integrations developed using GitLab 12.4 and earlier.

https://docs.gitlab.com/ee/api/groups.html#disabling-the-results-limit

I... don't have Rails access, we're using Gitlab.com not self-hosted. Would you recommend contacting Gitlab support?

**Comment by phillipj** [comment]
Yeay, great catch! I haven't been following along with the API docs lately, so not sure if that max limit of 100 has changed or not. I've convinced myself that was 1000 before, but I might be wrong.

Regardless, sounds like need to get pagination support in place for `gitlab-search` has increased.

Thanks for diving into this and finding the culprit 👍

**Comment by graham73may** [comment]
Awesome! Thanks for all the hard work, this tool is extremely useful <3

**Comment by phillipj** [comment]
Thanks for the kind words! Good to hear it brings value for others out there that needs it.

Kinda surprising GitLab still doesn't provide this out of the box with all the other goodies it has included, but guess it's just one of the things they wish to tease people over to being a paying customer for, which is totally understandable.

**Comment by phillipj** [comment]
In case someone stumbles upon this issue:

> Having the ability to enable debug logs have bugged me for a while, and your example serves as a good example why that would have been extremely valuable.

v1.2.0 just got published to npm, exposing debug logs by setting `$DEBUG=1` environment variable as described in the [Debugging section of README.md](https://github.com/phillipj/gitlab-search#debugging).

**Comment by martinbutt** [comment]
@phillipj this is an excellent tool. Thanks for sharing. Any update on adding pagination support?

**Comment by phillipj** [comment]
@martinbutt I'm afraid there's no update on this on my end. I started fiddling on it a while back, but obviously didn't finish it.

Would absolutely love seeing this fixed, and the code doesn't have to written by me. I fully understand it's challenging for external contributors when the source is written in ReasonML, which is pretty niche.

Thanks for the kind feedback and letting us know this would benefit more people out there.

**Comment by martinbutt** [comment]
Thanks, @phillipj. I did take a quick look and saw there would be a learning curve for me, so thought I'd check in first. If I find myself with some free time, I'll take a deeper look.

**Comment by phillipj** [comment]
Sooo with the much needed reminder from @martinbutt, I managed to have a new look at this...

Any chance you could give the changes proposed in PR #21 a spin as described in https://github.com/phillipj/gitlab-search/pull/21#issuecomment-812141176?

/cc @graham73may

**Comment by graham73may** [comment]
Next week I will be all over this like a rash 🥰!

**Comment by OlivierJaquemet** [comment]
Hi folks,

Using gitlab-search@1.5.0 it seems I only get a maximum of 20 results/match per projects.

The following [post on stackoverflow, in 2023](https://stackoverflow.com/questions/47414024/pagination-in-gitlab-api-only-returns-100-per-page-max) states :

> Check the response for the X-Total-Pages header. As long as page is smaller than total pages, you have to call the api again and increment the page variable. https://docs.gitlab.com/ee/api/rest/index.html#pagination-link-header

It is possible that the previous fix you implemented in this issue is no longer valid and that a maximum number of results is now always applied ?

Is any of you able to reproduce the problem ? Would you like another dedicated issue to be opened on this subject ?
