### ISSUE TITLE
Output archived-state of projects

### ISSUE THREAD

**Issue by flansch** [phillipj/gitlab-search#20]
As we've got a lot of archived projects, and they are often not relevant in searches, it would be really helpful to get a hint in the output if a project is archived. Or even better would be a parameter to restrict the search to projects that haven't been archived.

**Comment by phillipj** [comment]
This sounds really helpful indeed!

Ideally both of your suggestions would land some day, but they certainly wouldn't have to implemented at the same time.

**Comment by phillipj** [comment]
@flansch would something like the below suite your need to at least get a hint the repo in question is archived?

<img width="809" alt="Screenshot 2021-04-03 at 23 43 14" src="https://user-images.githubusercontent.com/1231635/113492249-67c7ed80-94d6-11eb-95ee-c81dfefda3c5.png">

**Comment by phillipj** [comment]
The `(archived)` indicator in the title landed and got published as v1.3.0.

In other words, the bonus feature of providing a filter to include/exclude archived projects is the last missing piece before this issue can be closed.

**Comment by flansch** [comment]
Sorry for answering so late. Today I tested your changes and it works great. It is really helpful to see which results are not relevant to me :-)
While filtering would be great it isn't really necessary.

**Comment by phillipj** [comment]
Yeay great to hear it's useful, thx for following up 👍🏻
