### ISSUE TITLE
Is it possible to search all branches?

### ISSUE THREAD

**Issue by graham73may** [phillipj/gitlab-search#23]
This might be a question about what's possible with Gitlab's API or it might be a feature request, I'm not sure... 

Is it possible to search *all* branches? I think currently the results are only based on the master branch?

**Comment by phillipj** [comment]
Myeah, I also feel this is mostly a GitLab API question.

The docs says it's possible to choose branch/tag via the `ref` parameter. When not provided, the repo/project' default branch is chosen: [GitLab Search API/Projects](https://docs.gitlab.com/ee/api/search.html#project-search-api).

There's ofcourse a creative way around this, where one could loop through all branches of any given repository and one search per branch, not just one per repository as today. Having in mind it's natural for git repositories to have many branches, I'd be reluctant introducing such a trick in `gitlab-search`, as that would most likely make a *big* difference for many users.

**Comment by systemsgo** [comment]
Is there a way to select the branch to search?  Ideally I'd like to be able to pass a comma separated list of branches and have gitlab-search include all of them in the search results.

**Comment by phillipj** [comment]
@systemsgo rephrasing my answer from earlier; yes, the GitLab API supports specifying the branch to search within. The `gitlab-search` tool does not have support for that as of now.
