### ISSUE TITLE
Add LICENSE

### ISSUE THREAD

**Issue by dnsmichi** [phillipj/gitlab-search#29]
Thanks for creating this project! 

I'd suggest adding a license, MIT or Apache.

**Comment by phillipj** [comment]
Hi there @dnsmichi, completely agree!

My intention was to MIT license it, hence what is mentioned in the README, but you raising this issue gives me a hint that isn't sufficient -- thanks 👍🏻

**Comment by dnsmichi** [comment]
@phillipj Oh, I completely overlooked it in the Readme, sorry :) My workflow is 1) project details on the right on GitHub 2) visually scan the repository listing for a license file. 

Thanks for adding it! Makes license scanning automation more easy too :)
