### ISSUE TITLE
Not getting full results

### ISSUE THREAD

**Issue by ThatRickGuy** [phillipj/gitlab-search#5]
We have an internal GitLab CE server (11.10.4). Our repos are set up in group\subgroup\projects for the most part. 

When I search for words, sometimes I get no results back (even though I can go to the repo with that keyword, use the UI search, and get multiple responses), or I get some results back (from one directory tree, but not others). 

The projects that return results appear to be consistent between each run, but I'm not seeing a pattern between which ones return and which do not. The account I used to generate the API token is a maintainer on all of the repos, but not a site admin.

**Comment by phillipj** [comment]
Thanks a lot for reporting!

Any chance those missing repositories belongs to an user account, ref #1?

If not, we'd have to do a little more digging.. At the moment there's no way to get more verbose information from the this tool, meaning there's no easy way to see which groups & projects it actually tries to perform searches in -- this is something that I've been wanting more than once.

With that in mind, the first thing that comes to mind is double checking that the GitLab REST API responds with the expected groups, projects and search results. More or less the main gist of what this tool does in its [`src/Main.re`](https://github.com/phillipj/gitlab-search/blob/master/src/Main.re#L21).

Here's a few HTTP requests against the API that might give some clues:

#### Get all groups

```
$  curl --request GET --header "PRIVATE-TOKEN: <your_access_token>" https://gitlab.example.com/api/v4/groups
```

https://docs.gitlab.com/ee/api/groups.html#list-groups

#### Get all projects within a group

```
$ curl --request GET --header "PRIVATE-TOKEN: <your_access_token>" https://gitlab.example.com/api/v4/groups/:group-id/projects
```

https://docs.gitlab.com/ee/api/groups.html#list-a-groups-projects


#### Search for contents inside a project

```
$ curl --request GET --header "PRIVATE-TOKEN: <your_access_token>" https://gitlab.example.com/api/v4/projects/:project-id/search?scope=blobs&search=<your-search-query>
```

https://docs.gitlab.com/ee/api/search.html#scope-blobs

**Comment by phillipj** [comment]
After posting my previous answer, I realised that we at work have usually organised repositories/projects into one level of groups. Just recently have we started introducing subgroups as well.

My first test targeted against projects within subgroups, doesn't yield any results as you're describing. In other words, I suspect this tool doesn't support subgroups at the moment.

**Comment by ThatRickGuy** [comment]
I think it's actually an easy fix after school me more testing.

If I hit the groups API, I only get 20 results, the same as the groups that the searcher successfully hits.

The API defaults to 20 items per page. So adding ?per_page=1000 got me all of the groups I was expecting.

I'm betting it's the same issue we're seeing here.

**Comment by ThatRickGuy** [comment]
We may have a similar issue with the projects API. Will likely need to add ?per_page=1000 to the fetchProjectsInGroups function as well.
